#!/usr/bin/env python

interfaces = input("Please enter number of interfaces?\n")

if interfaces > 3:
    print("Too many interfaces! This script is designed for 2 or 3 interfaces.")
    
elif interfaces == 3:
    inside = raw_input("Please specify the name of the inside lan interface? Ex. FastEthernet0/1\n")
    outside = raw_input("Please specify the name of the outside interface? Ex. FastEthernet0/0\n")
    additional = raw_input("Please specify the name of the additional interface?\n")
    print ("\n")
    print ("!!Copy after this line down!!\n")
    print ("policy-map type inspect InsideToOutside")
    print ("class class-default")
    print ("inspect")
    print ("!")
    print ("zone security Inside")
    print ("description Inside network")
    print ("zone security Outside")
    print ("description Outside network")
    print ("zone-pair security InsideToOutside source Inside destination Outside")
    print ("service-policy type inspect InsideToOutside")
    print ("!")
    print ("interface %s" %inside)
    print ("zone-member security Inside")
    print ("!")
    print ("interface %s" %outside)
    print ("zone-member security Outside\n")
    print ("!!End of config!!")

elif interfaces < 2:
    print ("You need at least 2 interfaces to configure the ZBFW.")

else:
    inside = raw_input("Please specify the name of the inside lan interface? Ex. FastEthernet0/1\n")
    outside = raw_input("Please specify the name of the outside interface? Ex. FastEthernet0/0\n")
    print ("\n")
    print ("!!Copy after this line down!!\n")
    print ("policy-map type inspect InsideToOutside")
    print ("class class-default")
    print ("inspect")
    print ("!")
    print ("zone security Inside")
    print ("description Inside network")
    print ("zone security Outside")
    print ("description Outside network")
    print ("zone-pair security InsideToOutside source Inside destination Outside")
    print ("service-policy type inspect InsideToOutside")
    print ("!")
    print ("interface %s" %inside)
    print ("zone-member security Inside")
    print ("!")
    print ("interface %s" %outside)
    print ("zone-member security Outside\n")
    print ("!!End of config!!")
